### ISSUE TITLE
Image not updating automatically  

### ISSUE THREAD

**Issue by serafinski** [avinal/Profile-Readme-WakaTime#41]
Hi, 
I have a problem with image updates with Actions -> automation seems to work - but I have to force the action manually for the image to update in my README. 

It doesn't seems to work, when it's done by automation - the image just won't update.

Can you tell me what am I doing wrong. I don't think it's a bug - cause it's working fine in your README.

Thanks in advance!
Tom

**Comment by avinal** [comment]
Hi @tomertin, I didn't understand your issue, is your image not updating after the action runs or the updated image doesn't shows up immediately in your readme?

If its the first case then there is some problem with the code logic and I will have to investigate it. But for the second case you don't need to worry. I will tell you why. The Readme acts like a web page but it is sanitized before the elements can show up. GitHub doesn't refreshes them too frequently in order to save bandwidth for more important tasks. So it may happen that image is updated but doesn't shows up immediately but that will automatically refresh after a period. So no need to worry amd there is nothing we can do from our end.
I am currently working on renovating the whole project to make it faster and add more options. But it will take some time.

**Comment by serafinski** [comment]
Hi @avinal,
the image is just not updating after the action runs automatically (via GitHub Actions, and script provided by You).   

So, for example - this image was generated at midnight CET on 26th of March - so, as a last date it should show 25th of March - but it stil showing 24th - thus it didn't update itself automatically. 
![stat](https://user-images.githubusercontent.com/88508650/160245221-d0bd8385-7c39-439f-bdea-abe150aac525.svg)

If I would trigger action manually - the image would update itself on my README after a few minutes.

Thanks for the reply - I'm really looking forward to the renovation!
Tom
